---
- name: Get current repository topics
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ github_username }}/{{ inventory_hostname }}/topics"
    method: GET
    headers:
      Authorization: "token {{ github_token }}"
      Accept: "application/vnd.github.mercy-preview+json"
    status_code: 200
  register: current_topics
  when: repo_topics is defined

- name: Set repository topics
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ github_username }}/{{ inventory_hostname }}/topics"
    method: PUT
    headers:
      Authorization: "token {{ github_token }}"
      Accept: "application/vnd.github.mercy-preview+json"
      Content-Type: "application/json"
    body_format: json
    body:
      names: "{{ repo_topics | default([]) }}"
    status_code: 200
  register: topics_result
  when: repo_topics is defined

- name: Display topics status
  ansible.builtin.debug:
    msg: >-
      {% if repo_topics is defined %}
      {% if current_topics.json.names != repo_topics %}
      Topics updated for {{ github_username }}/{{ inventory_hostname }}: {{ repo_topics | join(', ') }}
      {% else %}
      Topics already set for {{ github_username }}/{{ inventory_hostname }}: {{ repo_topics | join(', ') }}
      {% endif %}
      {% else %}
      No topics defined for {{ github_username }}/{{ inventory_hostname }}
      {% endif %}
  when: repo_topics is defined or current_topics is defined
